import type { SupplementType } from "./constants";

const questions: Array<{ text: string; supplements: Array<SupplementType> }> = [
  {
    text: "您排便的颜色经常是黑色或褐色（咖啡色）",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Probiotics",
      "DoubleX",
    ],
  },
  {
    text: "您经常胃酸过多或胃痛",
    supplements: [
      "Protein",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你经常腹泻或消化不良",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Probiotics",
      "DoubleX",
    ],
  },
  {
    text: "你经常有胃胀气现象",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你平常容易手脚冰冷",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你有贫血现象（易晕眩、体力差）",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "DoubleX",
    ],
  },
  {
    text: "你经常头痛",
    supplements: [
      "VitaminA",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你容易紧张，工作压力大",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "CalMagD",
      "DoubleX",
    ],
  },
  {
    text: "你容易健忘或集中力有衰退现象",
    supplements: ["LecithinE", "CalMagD", "Omega3", "DoubleX"],
  },
  {
    text: "你经常有抽筋现象",
    supplements: ["LecithinE", "CalMagD"],
  },
  {
    text: "你容易晕车或晕船",
    supplements: ["Protein", "VitaminB", "Garlic"],
  },
  {
    text: "你夜间视觉变得较差怕光",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你容易失眠，睡不着（多梦，易醒）",
    supplements: [
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你经常有筋骨酸痛现象",
    supplements: ["Protein", "VitaminC", "CalMagD", "DoubleX"],
  },
  {
    text: "你经常感冒",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "Probiotics",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你常常觉得疲倦或精神不好",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Probiotics",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你有血压偏高，血脂肪过高",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
    ],
  },
  {
    text: "你的鼻子皮肤有过敏现象",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "Probiotics",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你有尿酸，痛风现象",
    supplements: [
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你有血糖过高或有糖尿病症状",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你有体重过重现象",
    supplements: [
      "Protein",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你的背上长很多痘痘",
    supplements: [
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "Probiotics",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你经常对某些食物或保养品有过敏现象",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "Probiotics",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你有黑斑，雀斑，身体有不明的斑点",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "Probiotics",
      "DoubleX",
    ],
  },
  {
    text: "你经常口干舌燥，嘴角破裂，嘴角干裂",
    supplements: ["VitaminB", "VitaminC", "LecithinE"],
  },
  {
    text: "你有青春痘或粉刺",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "DoubleX",
    ],
  },
  {
    text: "你有气喘的毛病",
    supplements: [
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你的眼睛经常感觉到疲劳，干燥或刺痛",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Omega3",
    ],
  },
  {
    text: "你经常干咳",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你的生理期下腹会感觉疼痛",
    supplements: [
      "Protein",
      "VitaminB",
      "LecithinE",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你脱头发枯燥，容易分叉",
    supplements: ["Protein", "VitaminB", "VitaminC", "LecithinE", "DoubleX"],
  },
  {
    text: "你的指甲有白斑，条纹或者易断裂",
    supplements: ["Protein", "VitaminA", "VitaminC", "LecithinE", "DoubleX"],
  },
  {
    text: "你经常情绪不佳，暴躁，沮丧或忧郁",
    supplements: ["VitaminB", "VitaminC", "CalMagD", "DoubleX"],
  },
  {
    text: "你身体容易有淤血",
    supplements: ["Protein", "VitaminC", "CalMagD", "DoubleX"],
  },
  {
    text: "你的伤口不容易愈合",
    supplements: ["Protein", "VitaminA", "VitaminC", "LecithinE", "DoubleX"],
  },
  {
    text: "你头皮屑较多或经常头皮痒",
    supplements: ["Protein", "VitaminA", "VitaminB", "CalMagD", "DoubleX"],
  },
  {
    text: "你牙龈容易出血",
    supplements: ["Protein", "VitaminB", "VitaminC", "CalMagD", "DoubleX"],
  },
  {
    text: "你经常熬夜，睡眠不足。睡眠少于6小时",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "Probiotics",
      "Garlic",
      "DoubleX",
    ],
  },
  {
    text: "你平时容易赖床或起不来",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你没有每天定时排便或排便时不顺畅",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "DoubleX",
    ],
  },
  {
    text: "你常吃速食，零食，泡面等食物",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "Fibre",
      "Probiotics",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你每天吃蔬菜水果少于两次",
    supplements: [
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "DoubleX",
    ],
  },
  {
    text: "你经常节食以减轻体重",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你经常三餐不足或不定时用餐",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你经常吃宵夜",
    supplements: [
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你爱吃油炸食物",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你经常喝酒，抽烟",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "CalMagD",
      "Probiotics",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你经常打针吃药（包括中西药或补品）",
    supplements: [
      "Protein",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你不爱吃红萝卜",
    supplements: ["VitaminA", "DoubleX"],
  },
  {
    text: "你经常不吃早餐",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你没有每天喝牛奶或羊奶",
    supplements: ["Protein", "VitaminB", "CalMagD", "Probiotics", "DoubleX"],
  },
  {
    text: "你现在已经怀孕或在哺乳",
    supplements: [
      "Protein",
      "VitaminA",
      "VitaminB",
      "VitaminC",
      "LecithinE",
      "Fibre",
      "CalMagD",
      "Probiotics",
      "Garlic",
      "Omega3",
      "DoubleX",
    ],
  },
  {
    text: "你现在是长期吃素（素食者）",
    supplements: [
      "Protein",
      "VitaminB",
      "LecithinE",
      "Fibre",
      "Probiotics",
      "DoubleX",
    ],
  },
];

export default questions;
